version: '3'

services:
  https:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: 'test.leonas-play-list.com -> http://leonas-play-list:8899'
      STAGE: staging
    volumes:
      - https-portal-data:/var/lib/https-portal
    restart: always


  leonas-play-list:
    build:
      context: .
      dockerfile: leonas-play-list-dockerfile
    restart: always

  mongo:
    build:
      context: .
      dockerfile: mongo-dockerfile
#    restart: always
    volumes:
      - ./mongo:/data/db
      - ./mongo:/data/configdb
      - ./volumes/mongo/backup:/backup

  mongo-bk-cron:
    build:
      context: .
      dockerfile: dind-cron-dockerfile
    restart: always
    env_file: .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  https-portal-data:
  mongo:
