version: '3'

services:
  https:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: 'test.leonas-play-list.com -> http://leonas-play-list:8899'
      STAGE: staging
    volumes:
      - https-portal-data:/var/lib/https-portal

  leonas-play-list:
    build:
      context: .
      dockerfile: leonas-play-list-dockerfile

volumes:
  https-portal-data: