version: '3'

services:
  https:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: 'leonas-play-list.com -> http://leonas-play-list:8899'
      STAGE: production
    volumes:
      - https-portal-data:/var/lib/https-portal
#    restart: always


  leonas-play-list:
    environment:
      - TZ=Asia/Tokyo
    build:
      context: .
      dockerfile: leonas-play-list-dockerfile
#    restart: always

  mongo:
    environment:
      - TZ=Asia/Tokyo
    build:
      context: .
      dockerfile: mongo-dockerfile
#    restart: always
    volumes:
      - ./mongo:/data/db
      - ./mongo:/data/configdb
      - ./mongo/backup:/backup

  cron:
    environment:
      - TZ=Asia/Tokyo
    build:
      context: .
      dockerfile: dind-cron-dockerfile
#    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  https-portal-data:
  mongo:

